<a href="https://colab.research.google.com/github/sudhakar1504/Machine-Learning/blob/main/oneHoEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv('/content/carprices.csv')
df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [5]:
df.isna().sum()

Car Model        0
Mileage          0
Sell Price($)    0
Age(yrs)         0
dtype: int64

In [8]:
df['Car Model'].unique()

array(['BMW X5', 'Audi A5', 'Mercedez Benz C class'], dtype=object)

In [11]:
# prompt: get dummies for car model in int

dummies = pd.get_dummies(df['Car Model'], dtype=int)
dummies.head()

Audi A5  BMW X5  Mercedez Benz C class
0        0       1                      0
1        0       1                      0
2        0       1                      0
3        0       1                      0
4        0       1                      0

In [12]:
mergedf = pd.concat([df, dummies], axis='columns')
mergedf.head()

Car Model  Mileage  Sell Price($)  ...  Audi A5  BMW X5  Mercedez Benz C class
0    BMW X5    69000          18000  ...        0       1                      0
1    BMW X5    35000          34000  ...        0       1                      0
2    BMW X5    57000          26100  ...        0       1                      0
3    BMW X5    22500          40000  ...        0       1                      0
4    BMW X5    46000          31500  ...        0       1                      0

[5 rows x 7 columns]

In [13]:
X = mergedf.drop(['Car Model', 'Sell Price($)'], axis='columns')
X.head()

Mileage  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0    69000         6        0       1                      0
1    35000         3        0       1                      0
2    57000         5        0       1                      0
3    22500         2        0       1                      0
4    46000         4        0       1                      0

In [14]:
Y = mergedf['Sell Price($)']
Y.head()

0    18000
1    34000
2    26100
3    40000
4    31500
Name: Sell Price($), dtype: int64

In [15]:
#model
model = LinearRegression()
model.fit(X, Y)

LinearRegression()

In [17]:
model.score(X,Y)

0.9417050937281083

In [19]:
model.predict([[69000,	6,	0,	1,	0]])

array([18705.2723644])

In [20]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [48]:
#label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [52]:
carle = le.fit_transform(df['Car Model'])
carle

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [57]:
df1 = df
df1['Car Model'] = carle
df1

dfX = df1[['Car Model','Mileage','Age(yrs)']].values
dfX

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [62]:
testX = df1.drop(['Sell Price($)'], axis='columns').values
testX
dfY = df1['Sell Price($)']
dfY

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [76]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('Car Model', OneHotEncoder(), [0])], remainder='passthrough')
ct = ct.fit_transform(dfX)
ct

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [73]:
df1['Mileage'].unique()

array([69000, 35000, 57000, 22500, 46000, 59000, 52000, 72000, 91000,
       67000, 83000, 79000])

In [77]:
#model
nm = LinearRegression()
nm.fit(ct, dfY)

LinearRegression()

In [79]:
nm.predict([[0,0,1,45000,4]])

array([36991.31721061])

In [81]:
nm.predict([[0,1,0,86000,7]])

array([11080.74313219])

In [82]:
nm.score(ct,dfY)

0.9417050937281083